routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', 'PagesController@index')->name('pages.home');
Route::get('nosotros', 'PagesController@about')->name('pages.about');
Route::get('archivo', 'PagesController@archive')->name('pages.archive');
Route::get('contacto', 'PagesController@contact')->name('pages.contact');


// public function show(Post $post) recuerda que necesita un parametro $post = post
Route::get('blog/{post}', 'PostsController@show')->name('posts.detail');
// Buscar por categoria
Route::get('/categorias/{category}', 'CategoriesController@searchCategory')->name('search.category');
// Buscar por etiquetas - tags
Route::get('/tags/{tag}', 'TagsController@searchTag')->name('search.tag');
// Rutas para obtener y procesar la suscripcion
Route::group(['middleware' => ['auth']], function () {
    Route::group(["prefix" => "admin", 'namespace' => 'admin'], function() {


        Route::get('/', 'HomeController@index')->name('home');
        // Administrar los post y user
        Route::resource('posts', 'PostsController',['except' => 'show']);
        Route::resource('users', 'UsersController');
        // Administrar Roles
        Route::resource('roles', 'RolesController',['except' => 'show']);
        // Administrar Permisos
        Route::resource('permissions', 'PermissionsController', ['only' => ['index', 'edit', 'update']]);


        // Administrar los roles y solo pueden actualizar los roles los que tienen rol de admnistrador
        Route::middleware('role:Admin')->put('users/{user}/roles', 'UsersRolesController@update')->name('users.roles.update');
        // Administrar los permisos  y solo pueden actualizar los permisos los que tienen rol de admnistrador
        Route::middleware('role:Admin')->put('users/{user}/permissions', 'UsersPermissionsController@update')->name('users.permissions.update');

        // Administrar las photos
        Route::post('posts/{post}/photos', 'PhotoController@store')->name('posts.photos.store');
        Route::delete('photos/{photo}', 'PhotoController@destroy')->name('admin.photos.destroy');
    });

});

Route::auth();

app/Http/Controllers/Admin/RolesController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

use App\Http\Requests\SaveRolesRequest;

class RolesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

            return view('admin.roles.index', [
                'roles' => Role::all()
                ]);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('create',$role = new Role);
        $btnText = __("Crear Role");
        return view('admin.roles.form', [
            'role' => $role,
            'permissions' => Permission::pluck('name', 'id'),

        ],compact('btnText'));

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(SaveRolesRequest  $request)
    {
        $this->authorize('create', new Role);

        $role = Role::create($request->validated());


       if ($request->has('permissions'))
        {
            // le asigno los permisos al rol
            $role->givePermissionTo($request->permissions);
        }

        return redirect()->route('roles.index')->with('message', ['success', __('El role fue creado correctamente')]);

    }



    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Role $role)
    {
        $this->authorize('update', $role);

        $btnText = __("Editar Role");
        //
        return view('admin.roles.form', [
            'role' => $role,
            'permissions' => Permission::pluck('name', 'id')
        ],compact('btnText'));
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(SaveRolesRequest  $request, Role $role)
    {
        $this->authorize('update', $role);

        $role->update($request->validated());

        // elimina todas sus relaciones el rol con sus permisos
        // y los elimina
        $role->permissions()->detach();

        // si es que tiene permisos el rol los va a asociar nuevamente
        if ($request->has('permissions'))
        {
            // tabla role_has_permissions
            $role->givePermissionTo($request->permissions);
        }

        return redirect()->route('roles.edit', $role)->with('message', ['success', __('El role fue actualizado correctamente')]);

    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Role $role)
    {
        $this->authorize('delete',$role);

        try {
            $role->delete();
            return back()->with('message', ['success', __("Role eliminado correctamente")]);
        } catch (\Exception $exception) {
            return back()->with('message', ['danger', __("Error eliminando el Role")]);
        }
    }
}

resources/views/admin/roles/checkboxes.blade.php
@forelse ($roles as $role)
    <div class="checkbox">
        <label>
            <input name="roles[]" type="checkbox" value="{{ $role->name }}" {{ $user->roles->contains($role->id) ? 'checked' : '' }}>
            {{ $role->name }} <br>
            <small class="text-muted">{{ $role->permissions->pluck('name')->implode(', ')}}</small>
        </label>
    </div>

@empty

@endforelse

resources/views/admin/roles/form.blade.php
@extends('admin.layout')
@section('header')

@endsection
@section('content')
    <div class="row">

        <form
                method="POST"
                {{--Si no exite el id del curso se va procesar store (guardar una nuevo )
                si lo tiene solo va actualizar el id del regustro y ademas le paso el slug --}}
                action="{{ ! $role->id ? route('roles.store') : route('roles.update', ['id' => $role->id])}}"
                {{--que no valide el navegador --}}
                novalidate

        >

            @if($role->id)
                @method('PUT')
            @endif

            @csrf


            <div class="col-md-6">

                <div class="box box-warning">
                    <div class="box-header">
                        <h3 class="box-title">Roles</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        @if ($role->exists)
                            <div class="form-group has-feedback">
                                <label for="name">
                                    {{ __("Identificador") }}
                                </label>
                                <input
                                        name="name"
                                        id="name"
                                        class="form-control"
                                        value="{{ $role->name }}"
                                        disabled
                                />
                            </div>
                        @else
                            <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }} has-feedback">
                                <label for="name">
                                    {{ __("Identificador") }}
                                </label>
                                <input
                                        name="name"
                                        id="name"
                                        class="form-control"
                                        value="{{ old('name') ?: $role->name }}"

                                />

                                @if ($errors->has('name'))
                                    <span class="help-block" role="alert">
                                                {{ $errors->first('name') }}
                                </span>
                                @endif
                            </div>
                        @endif

                            <div class="form-group{{ $errors->has('display_name') ? ' has-error' : '' }} has-feedback">
                                <label for="display_name">
                                    {{ __("Nombre") }}
                                </label>
                                <input
                                        name="display_name"
                                        id="display_name"
                                        class="form-control"
                                        value="{{ old('display_name') ?: $role->display_name }}"

                                />

                                @if ($errors->has('display_name'))
                                    <span class="help-block" role="alert">
                                                {{ $errors->first('display_name') }}
                                </span>
                                @endif
                            </div>

                        <div class="form-group col-md-6">
                            <label>Permisos</label>
                            @include('admin.permissions.checkboxes', ['model' => $role])
                        </div>


                        <div class="form-group">
                            <button type="submit" class="btn btn-primary btn-block">
                                {{ __($btnText) }}
                            </button>
                        </div>
                    </div>
                </div>
            </div>

        </form>


    </div>

@endsection

resources/views/admin/roles/index.blade.php
@extends('admin.layout')

@section('header')
    <h1>
        Roles
        <small>Listado</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="{{ route('home') }}"><i class="fa fa-dashboard"></i> Inicio</a></li>
        <li class="active">Roles</li>
    </ol>
@stop

@section('content')
    <div class="box box-primary">
        <div class="box-header">
            <h3 class="box-title">Listado de Roles</h3>
            @can('create', $roles->first())
            <a href="{{ route('roles.create') }}" class="btn btn-primary pull-right">
                <i class="fa fa-plus"></i>  Crear Role
            </a>
            @endcan
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            <table id="roles-table" class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Identificador</th>
                    <th>Nombre</th>
                    <th>Permisos</th>
                    <th>Acciones</th>
                </tr>
                </thead>
                <tbody>
                @foreach ($roles as $role)
                    <tr>
                        <td>{{ $role->id }}</td>
                        <td>{{ $role->name }}</td>
                        <td>{{ $role->display_name }}</td>
                        <td>{{ $role->permissions->pluck('display_name')->implode(', ') }}</td>

                        <td>
                            @can('update', $role)
                            <a href="{{ route('roles.edit', $role) }}"
                               class="btn btn-xs btn-info"
                            ><i class="fa fa-pencil"></i></a>
                            @endcan

                            @can('delete', $role)
                                @if ($role->id !== 1)
                                <form method="POST"
                                      action="{{ route('roles.destroy', $role) }}"
                                      style="display: inline">
                                    {{ csrf_field() }} {{ method_field('DELETE') }}
                                    <button class="btn btn-xs btn-danger"
                                            onclick="return confirm('¿Estás seguro de querer eliminar esta Role?')"
                                    ><i class="fa fa-times"></i></button>
                                </form>
                                @endif
                            @endcan
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
        <!-- /.box-body -->
    </div>
    <!-- /.box -->
@stop

@push('styles')
    <link href="/css/datatables.css" rel="stylesheet">
@endpush

@push('scripts')
    <script src="/js/datatables.js" ></script>
    <script>
        $(function () {
            $("#roles-table").DataTable(
                {
                    "paging": true,
                    "lengthChange": false,
                    "searching": false,
                    "ordering": true,
                    "info": true,
                    "autoWidth": false
                }
            );
        });
    </script>
@endpush