routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', 'PagesController@index')->name('pages.home');
Route::get('nosotros', 'PagesController@about')->name('pages.about');
Route::get('archivo', 'PagesController@archive')->name('pages.archive');
Route::get('contacto', 'PagesController@contact')->name('pages.contact');


// public function show(Post $post) recuerda que necesita un parametro $post = post
Route::get('blog/{post}', 'PostsController@show')->name('posts.detail');
// Buscar por categoria
Route::get('/categorias/{category}', 'CategoriesController@searchCategory')->name('search.category');
// Buscar por etiquetas - tags
Route::get('/tags/{tag}', 'TagsController@searchTag')->name('search.tag');
// Rutas para obtener y procesar la suscripcion
Route::group(['middleware' => ['auth']], function () {
    Route::group(["prefix" => "admin", 'namespace' => 'admin'], function() {


        Route::get('/', 'HomeController@index')->name('home');
        // Administrar los post y user
        Route::resource('posts', 'PostsController',['except' => 'show']);
        Route::resource('users', 'UsersController');
        // Administrar Roles
        Route::resource('roles', 'RolesController',['except' => 'show']);
        // Administrar Permisos
        Route::resource('permissions', 'PermissionsController', ['only' => ['index', 'edit', 'update']]);


        // Administrar los roles y solo pueden actualizar los roles los que tienen rol de admnistrador
        Route::middleware('role:Admin')->put('users/{user}/roles', 'UsersRolesController@update')->name('users.roles.update');
        // Administrar los permisos  y solo pueden actualizar los permisos los que tienen rol de admnistrador
        Route::middleware('role:Admin')->put('users/{user}/permissions', 'UsersPermissionsController@update')->name('users.permissions.update');

        // Administrar las photos
        Route::post('posts/{post}/photos', 'PhotoController@store')->name('posts.photos.store');
        Route::delete('photos/{photo}', 'PhotoController@destroy')->name('admin.photos.destroy');
    });

});

Route::auth();

app/Post.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;


class Post extends Model
{

    // para que laravel se de cuenta que tambien tiene formato de fecha
    protected $dates = ['published_at'];
    // solo los campos que estas asignado se van a actualizar
    protected $fillable = ['title', 'excerpt', 'body','iframe', 'category_id','published_at','slug','user_id'];



    public static function boot ()
    {
        parent::boot();


        // Cuando se este eliminado se elimine sus relaciones
        static::deleting(function($post){
            if (!\App::runningInConsole()) {
                $post->tags()->detach();
                $post->photos->each->delete();
            }
        });

    }



    // Cada post tiene una categoria
    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function tags()
    {
        return $this->belongsToMany(Tag::class);
    }

    public function photos() {
        return $this->hasMany(Photo::class);
    }

    // Cada post tiene un usuario
    public function owner()
    {
        return $this->belongsTo(User::class,'user_id');
    }

    public function scopePublished($query)
    {
        $query->with(['category','tags','owner','photos'])
            ->whereNotNull('published_at')
            ->where('published_at','<=', Carbon::now())
            ->latest('published_at');
    }

    // scope que sirve para listar los post solo del admin(todos)
    // y el escritor que filtre solo sus posts
    public function scopeallowed($query)
    {
        // Le pasamos la funcion can  los datos del $post
        // esto se ira al metodo Policies/PostPolicy y vera la funcion view
        // la cual dice que si el post le pertenece o sino si es que
        // tiene el permiso View post (TABLA PERMISSIONS Y MODEL_HAS_PERMISSIONS) si es que estan asociados pueden ver todos los post
        if (auth()->user()->can('view',$this))
        {
            return  $query;
        }
        else
        {
            // aqui el user_id de la tabla post debe de ser igual al id
            // del usuario autenticado
            return $query->where('user_id', auth()->id());
        }
    }

    // Slug para redifirigir a cda post por detalle
    public function getRouteKeyName() {
        return 'slug';
    }

   // $postRequest->get('published_at') esto lo recibimos de PostController
    //y es recibida como parametro ($published_at );
    public function setPublishedAtAttribute($published_at)
    {
        $now = Carbon::now();
        //                                   si tiene un valor
        $this->attributes['published_at'] = $published_at
        // procesmos la fecha con carbon
                                        ? Carbon::parse($published_at . $now->format('H:i:s'))->toDateTimeString()
            // de lo contrario devolvemos nulo
                                        : null;
    }

    //   $postRequest->get('category_id') esto lo recibimos de PostController
    //y es recibida como parametro ($category_id );
    public function setCategoryIdAttribute($category_id)
    {
        $this->attributes['category_id'] = Category::find($category_id)
                                        ? $category_id
                                        : Category::create(['name' => $category_id ])->id;
    }

    public function syncTags($tags)
    {
        $tagId = collect($tags)->map(function ($tag)
            {
                 // si lo encuentro solo retorno las etiquetas que estan ahi
                return   Tag::find($tag)
                        ? $tag
                        // de lo contrario los creo y obtenemos sus id
                        : Tag::create(['name' => $tag ])->id;
            });
        // como estamos dentro del modelo Post ya no es necesario $post->
        //  $post->tags()->sync($tags);
        return $this->tags()->sync($tagId);
    }

    //   $post = Post::create([ 'title' => $postRequest->get('title')]);
    // Dentro de mi Controlador Admin/PostsController dentro del metodo store
    // sobreescribire el me metodo pero previamnte le pasamos los atributos
    public static function create( $attributes = [])
    {
        $post = static::query()->create($attributes);

        $post->generateUrl();

        return $post;
    }

    public function generateUrl()
    {
        $url = str_slug($this->title);

        // si existe el slug a ese slug solo le agregas su id
        if ($this->whereSlug($url)->exists())
        {
            $url = "{$url}-{$this->id}";
        }

        $this->slug = $url;

        $this->save();
    }

    // Para que sea publica mi post
    // la fecha del post debe de ser diferente de nulo
    // ademas debe de ser menor a la fecha actual
    public function isPublished()
    {
        return ! is_null($this->published_at) && $this->published_at < today();
    }

    public function scopeByYearAndMonth($query)
    {
        return $query->selectRaw('year(published_at) year')
            ->selectRaw('month(published_at) month')
            ->selectRaw('monthname(published_at) monthname')
            ->selectRaw('count(*) posts')
            ->groupBy('year', 'month', 'monthname')
            ->orderBy('published_at');
    }


    public function viewType($home = '')
    {
        if ($this->photos->count() === 1) :
        return 'posts.photo';
        elseif($this->photos->count() > 1):
            return $home === 'home' ?  'posts.carousel-preview' : 'posts.carousel';
        elseif($this->iframe):
            return 'posts.iframe';
        else:
            return 'posts.text';
        endif;
    }





}

app/Http/Controllers/Admin/PostsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use App\Http\Requests\PostRequest;
use App\Post;
use App\Tag;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Carbon;

class PostsController extends Controller
{
    public function index()
    {
        // mostrar los posts solo del usuario
       // $posts = auth()->user()->posts;

        $posts = Post::allowed()->get();
        return view('admin.post.index',compact('posts'));
    }

     public function store(PostRequest $postRequest)
    {
        $this->authorize('create',new Post);

        // solo se guardara el titutlo por los demas son null
        $post = Post::create([
            'title' => $postRequest->get('title'),
            'user_id' => auth()->id()
        ]);
        return redirect()->route('posts.edit', compact('post'));
    }


    public function edit(Post $post)
    {
        // le ponemos la autorizacion y le mandamos el nombre de la funcion
        // que esta en Post/Policy y como segundo parametro le pasamos el objeto que
        // queremos autorizar
        $this->authorize('update',$post);
        $btnText = __("Guardar Publicacion");
        $post = Post::with(['category','tags'])->whereSlug($post->slug)->first();
        return view('admin.post.form', compact('post','btnText'));
    }

    public function update(Post $post, PostRequest $postRequest )
    {
        $this->authorize('update',$post);
         /*  // return $postRequest->all();
            $post->title = $postRequest->get('title');
            $post->excerpt = $postRequest->get('excerpt');
            $post->body = $postRequest->get('body');
            $post->iframe = $postRequest->get('iframe');
            // en nuestra vista el select de category es  name="category_id" por eso lo obtengo el valor de category_id
            // si la categoria es encontrada solo retorna la categoria hallada ? $cat
            // pero si no lo encuentra  crea una nueva categoria y le asigna un id
            // siempre y cuando en la validacion debe comentar esto // Rule::exists('categories', 'id')
            $post->category_id = $postRequest->get('category_id');
            $post->published_at =  $postRequest->get('published_at');
            $post->save();*/

        // Finalmente esos tags se asignaran
        // en nuestra vista el select de tags es  name="tags[]" por eso lo obtengo todos los valores tags
            $post->update($postRequest->all());
            $post->syncTags($postRequest->get('tags'));
        // luego enviamos un mensaje de exito de envio
        return redirect()->route('posts.edit', compact('post'))->with('message', ['success', __('Post editado correctamente')]);
    }

    public function destroy(Post $post)
    {
        $this->authorize('delete',$post);
        $post->delete();

        return redirect()
            ->route('posts.index')
            ->with('message', ['success', __('La publicacion ha sido eliminada')]);
    }



}

app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

use App\Post;
use Illuminate\Http\Request;

class PostsController extends Controller
{
    public function show(Post $post)
    {
      // si es que cumple las condiciones para que sea publica
      // o esta autenticado
      // puede ver el detalle del post

        if ($post->isPublished() || auth()->check()) {

            return view('posts.show', compact('post' ));
        }

        abort(404);


    }



}

resources/views/admin/post/form.blade.php
@extends('admin.layout')
@section('header')
    <h1>
       Posts
        <small>Crear publicacion</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="/admin"><i class="fa fa-dashboard"></i>Inicio</a></li>
        <li><a href="{{ route('posts.index') }}"><i class="fa fa-dashboard"></i>Posts</a></li>
    </ol>
@endsection
@section('content')
    <div class="row">
        {{--si es que tiene imagen muestra las fotos de lo contrario no muestra nada--}}
        @if ($post->photos->count())
            <div class="col-md-12">
                <div class="box box-primary">
                    <div class="box-body">
                        <div class="row">
                            @foreach ($post->photos as $photo)
                                <form method="POST" action="{{ route('admin.photos.destroy',$photo) }}">
                                    @csrf
                                    @method('DELETE')
                                    <div class="col-md-2">
                                        <button type="submit" class="btn btn-danger btn-xs" style="position: absolute">
                                            <i class="fa fa-remove"></i>
                                        </button>
                                        <img class="img-responsive" src="/storage/{{ $photo->url }}" alt="">
                                    </div>
                                </form>
                            @endforeach
                        </div>
                    </div>
                </div>
            </div>
        @endif
        <form
                method="POST"
                {{--Si no exite el id del curso se va procesar store (guardar una nuevo )
                si lo tiene solo va actualizar el id del regustro y ademas le paso el slug --}}
                action="{{ ! $post->id ? route('posts.store') : route('posts.update', ['slug' => $post->slug])}}"
                {{--que no valide el navegador --}}
                novalidate
                {{--subida de archivos --}}
                enctype="multipart/form-data"

        >

            {{--si estamos en modo edicion usamos el metodo PUT--}}
            @if($post->id)
                @method('PUT')
            @endif

            @csrf
            <div class="col-md-8">

                <div class="box box-warning">
                    <div class="box-header">
                        <h3 class="box-title">Crear Post</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">

                            <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }} has-feedback">
                                <label for="name">
                                    {{ __("Titulo de la publicacion") }}
                                </label>
                                    <input
                                            name="title"
                                            id="title"
                                            class="form-control"
                                            value="{{ old('title') ?: $post->title }}"
                                            placeholder="Ingrese aqui el titulo de la publicacion"
                                            autofocus
                                    />

                                    @if ($errors->has('title'))
                                        <span class="help-block" role="alert">
                                                {{ $errors->first('title') }}
                                            </span>
                                    @endif
                             </div>
                            <div class="form-group{{ $errors->has('body') ? ' has-error' : '' }} has-feedback">
                                <label for="body">
                                    {{ __("Contenido de la publicacion") }}
                                </label>
                                <textarea
                                        name="body"
                                        id="editor"
                                        class="form-control"
                                        placeholder="Ingrese aqui el contenido completo de la publicacion"
                                        autofocus
                                        rows="10"
                                >{{ old('body') ?: $post->body }}</textarea>

                                @if ($errors->has('body'))
                                    <span class="help-block" role="alert">
                                                {{ $errors->first('body') }}
                                            </span>
                                @endif
                            </div>
                            <div class="form-group has-feedback">
                                <label for="iframe">
                                    {{ __("Contendido Embebido (Iframe)") }}
                                </label>
                                <textarea
                                        name="iframe"
                                        id="iframe"
                                        class="form-control"
                                        autofocus
                                        placeholder="Ingresa contendido embebido (iframe) de audio o video"
                                        rows="2"
                                >{{ old('iframe') ?: $post->iframe }}</textarea>

                            </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="box box-warning">
                    <div class="box-body">

                        <div class="form-group {{ $errors->has('published_at') ? ' has-error' : '' }} has-feedback">
                            <label for="published_at">
                                {{ __("Fecha de Publicacion") }}
                            </label>
                            <div class="input-group date">
                                <div class="input-group-addon">
                                    <i class="fa fa-calendar"></i>
                                </div>
                                <input
                                        name="published_at"
                                        id="datepicker"
                                        class="form-control pull-right"
                                        value="{{ old('published_at') ?: ( $post->published_at ? $post->published_at->format('m/d/Y') : null ) }}"
                                />
                                @if ($errors->has('published_at'))
                                    <span class="help-block" role="alert">
                                                        {{ $errors->first('published_at') }}
                                                    </span>
                                @endif
                            </div>
                            <!-- /.input group -->
                        </div>
                        <div class="form-group {{ $errors->has('tags') ? ' has-error' : '' }}">
                            <label for="tags" >{{ __("Tag del Posts") }}</label>
                            <select name="tags[]" id="tags" class="form-control select2" multiple="multiple" data-placeholder="Selecciona una o mas etiquetas" style="width: 100%">
                                @foreach(\App\Tag::groupBy('name')->pluck('name', 'id') as $id => $tag)
                                    {{--Preguntamos si el old('tags') contiene el id si es verdadero se agrega la clase select--}}
                                    <option {{ (int) collect(old('tags',$post->tags->pluck('id')))->contains($id) ? 'selected' : '' }} value="{{ $id }}">
                                        {{ $tag }}
                                    </option>
                                @endforeach
                            </select>
                            @if ($errors->has('tags'))
                                <span class="help-block" role="alert">
                                                        {{ $errors->first('tags') }}
                                                    </span>
                            @endif
                        </div>
                        <div class="form-group{{ $errors->has('category_id') ? ' has-error' : '' }} has-feedback">
                            <label for="category_id" >{{ __("Categoría del Posts") }}</label>
                                <select name="category_id" id="category_id" class="form-control select2">
                                    {{--le agrego un order by porque para evitar que se repitan las categorias
                                    si se cae por el groupBy entonces anda config/database y cambia  'strict' => false --}}
                                    <option  value="">
                                        {{ __("Seleccione una categoria") }}
                                    </option>
                                    @foreach(\App\Category::groupBy('name')->pluck('name', 'id') as $id => $category)
                                        <option {{ (int) old('category_id') === $id || $post->category_id === $id ? 'selected' : '' }} value="{{ $id }}">
                                            {{ $category }}
                                        </option>
                                    @endforeach
                                </select>
                            @if ($errors->has('category_id'))
                                <span class="help-block" role="alert">
                                                        {{ $errors->first('category_id') }}
                                                    </span>
                            @endif
                        </div>
                        <div class="form-group{{ $errors->has('excerpt') ? ' has-error' : '' }} has-feedback">
                            <label for="excerpt">
                                {{ __("Extracto  de la publicacion") }}
                            </label>
                            <textarea
                                    name="excerpt"
                                    id="excerpt"
                                    class="form-control"
                                    placeholder="Ingrese aqui el extracto  de la publicacion"
                                    autofocus
                                    rows="3"
                            >{{ old('excerpt') ?: $post->excerpt }}</textarea>
                            @if ($errors->has('excerpt'))
                                <span class="help-block" role="alert">
                                                        {{ $errors->first('excerpt') }}
                                                    </span>
                            @endif
                        </div>
                        <div class="form-group">
                            <div class="dropzone">

                            </div>
                        </div>
                        <div class="form-group">
                           <button type="submit" class="btn btn-primary btn-block">
                               {{ __($btnText) }}
                           </button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>

@endsection
@push('styles')
    <link href="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.5.1/dropzone.css" rel="stylesheet">
    <link href="/css/datepicker3select2.css" rel="stylesheet">
@endpush
@push('scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.5.1/min/dropzone.min.js"></script>
    <script src="https://cdn.ckeditor.com/4.9.2/standard/ckeditor.js"></script>
    <script src="/js/datepicker3select2.js" ></script>
    <script>
        //Date picker
        $('#datepicker').datepicker({
            autoclose: true
        });
        // iniciar el select 2
        $(".select2").select2(
            {
                // permite escribit y agregar como un dato al select de
                // categoria como los tags por le ponemos tags : true
                tags : true
            }
        );
        // iniciar el content
        CKEDITOR.replace('editor');
        // alto del contendido   del formulario
        CKEDITOR.config.height = 315;

        // que inicie dropzone con la variable dropzone que se declaro en el html
        // lo guardamos en una variables
       var mydropzone =  new Dropzone('.dropzone',{
            url : '/admin/posts/{{ $post->slug }}/photos',
            paramName : 'photo',
            // validamos que los archivos subidos sean imagenes con cualquierea extension por eso le ponemos *
            acceptedFiles : 'image/*',
            // tamaño de la imagen de 2MB
            maxFilesize: 2 ,
           // cantidad de Imagenes
           //maxFiles: 1 ,
            // le pasamos el token
            headers : {
                'X-CSRF-TOKEN': '{{ csrf_token() }}'
            },
            // cambiamos el mensaje por defecto que aparece en el panel de imagenes
            dictDefaultMessage : 'Arrastra las fotos para subirlas'
        });

       // aca escuchamos los erros y enviamos con una funcion
        // el archivo , y la respuesta del servidor
       mydropzone.on('error', function (file, res) {
           // console.log(res.errors.photo[0]);
           var msg = res.errors.photo[0];
            $('.dz-error-message:last > span').text(msg);
       });
        // que no lo inicie automaticamente
        Dropzone.autoDiscover = false;

    </script>
@endpush

resources/views/admin/post/index.blade.php
@extends('admin.layout')
@section('header')
    <h1>
        Todas las publicaciones
        <small>Optional description</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i>Inicio</a></li>
        <li class="active">Posts</li>
    </ol>
@endsection
@section('content')
    <div class="box box-primary">
        <div class="box-header">
            <h3 class="box-title">Listado de Publicaciones</h3>
            <button class="btn btn-primary pull-right" data-toggle="modal" data-target="#myModal"><i class="fa fa-plus"></i> Crear Publicacion</button>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            <table id="posts-table" class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Titulo</th>
                    <th>Extracto</th>
                    <th>Acciones</th>
                </tr>
                </thead>
                <tbody>
                @forelse($posts as $post)
                <tr>
                    <td>{{ $post->id }}</td>
                    <td>{{ $post->title }}</td>
                    <td>{{ $post->excerpt }}</td>
                    <td>
                        <a href="{{ route('posts.detail',$post) }}" target="_blank" class="btn btn-xs btn-default"><i class="fa fa-eye"></i></a>
                        <a href="{{ route('posts.edit',$post) }}" class="btn btn-xs btn-info"><i class="fa fa-pencil"></i></a>
                        <form method="POST"
                              action="{{ route('posts.destroy', $post) }}"
                              style="display: inline">
                            {{ csrf_field() }} {{ method_field('DELETE') }}
                            <button class="btn btn-xs btn-danger"
                                    onclick="return confirm('¿Estás seguro de querer eliminar esta publicación?')"
                            ><i class="fa fa-times"></i></button>
                        </form>

                    </td>
                </tr>
                @empty   {{--le dices que no hay cursos --}}
                <div class="alert alert-dark">
                    {{ __("No hay ningún curso disponible") }}
                </div>
                @endforelse

                </tbody>
            </table>
        </div>
        <!-- /.box-body -->
    </div>
@endsection
@section('scripts')

@endsection
@push('styles')
    <link href="/css/datatables.css" rel="stylesheet">
@endpush
@push('scripts')
    <script src="/js/datatables.js" ></script>
    <script>
        $(function () {
            $('#posts-table').DataTable({
                "paging": true,
                "lengthChange": false,
                "searching": false,
                "ordering": true,
                "info": true,
                "autoWidth": false
            });
        });
    </script>
@endpush