routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', 'PagesController@index')->name('pages.home');
Route::get('nosotros', 'PagesController@about')->name('pages.about');
Route::get('archivo', 'PagesController@archive')->name('pages.archive');
Route::get('contacto', 'PagesController@contact')->name('pages.contact');


// public function show(Post $post) recuerda que necesita un parametro $post = post
Route::get('blog/{post}', 'PostsController@show')->name('posts.detail');
// Buscar por categoria
Route::get('/categorias/{category}', 'CategoriesController@searchCategory')->name('search.category');
// Buscar por etiquetas - tags
Route::get('/tags/{tag}', 'TagsController@searchTag')->name('search.tag');
// Rutas para obtener y procesar la suscripcion
Route::group(['middleware' => ['auth']], function () {
    Route::group(["prefix" => "admin", 'namespace' => 'admin'], function() {


        Route::get('/', 'HomeController@index')->name('home');
        // Administrar los post y user
        Route::resource('posts', 'PostsController',['except' => 'show']);
        Route::resource('users', 'UsersController');
        // Administrar Roles
        Route::resource('roles', 'RolesController',['except' => 'show']);
        // Administrar Permisos
        Route::resource('permissions', 'PermissionsController', ['only' => ['index', 'edit', 'update']]);


        // Administrar los roles y solo pueden actualizar los roles los que tienen rol de admnistrador
        Route::middleware('role:Admin')->put('users/{user}/roles', 'UsersRolesController@update')->name('users.roles.update');
        // Administrar los permisos  y solo pueden actualizar los permisos los que tienen rol de admnistrador
        Route::middleware('role:Admin')->put('users/{user}/permissions', 'UsersPermissionsController@update')->name('users.permissions.update');

        // Administrar las photos
        Route::post('posts/{post}/photos', 'PhotoController@store')->name('posts.photos.store');
        Route::delete('photos/{photo}', 'PhotoController@destroy')->name('admin.photos.destroy');
    });

});

Route::auth();

app/User.php
<?php

namespace App;

use Spatie\Permission\Traits\HasRoles;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

/**
 * App\User
 *
 * @property-read \Illuminate\Notifications\DatabaseNotificationCollection|\Illuminate\Notifications\DatabaseNotification[] $notifications
 * @mixin \Eloquent
 */
class User extends Authenticatable
{
    use Notifiable,HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    // Para devolver el password encriptado
    // y en registerController
    // 'password' => Hash::make($data['password']),
    // deshabilitar el Hash::make para evitar doble encriptacion
    public function setPasswordAttribute($password)
    {
        $this->attributes['password'] = bcrypt($password);
    }



    // cada usuario tiene muchos post
    public function posts() {
        return $this->hasMany(Post::class);
    }

    public function scopeAllowed($query)
    {
        // si es que el usuario tiene permiso del metodo view puede ver todos los usuarios
        // $THIS => le enviamos el usuario
       /* public function view(User $authUser, User $user)
        {
            // $authUser =   usuario autenticado
            // $user     =   el id del usuario
            return $authUser->id === $user->id || $user->hasPermissionTo('View users');
        }*/

       // Si es que no eres un administrador solo podras ver a ti mismo
        if( auth()->user()->can('view', $this) )
        {
            return $query;
        }

        // caso contrario solo puede puede ver solo
        return $query->where('id', auth()->id());
    }


    public function getRoleDisplayNames()
    {
        return $this->roles->pluck('display_name')->implode(', ');
    }


}

app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Events\UserWasCreated;
use App\Http\Requests\UserRequest;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;


class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::get();
        return view('admin.user.index',compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        $user = new User;

        $this->authorize('create', $user);

        $roles = Role::with('permissions')->get();
        $permissions = Permission::pluck('name','id');
        $btnText = __("Crear Usuario");
        return view('admin.user.create', compact('user','btnText','roles','permissions'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->authorize('create', new User);
       // Validar el formulario
        $data = $request->validate([
            'name' => 'required|max:255',
            'email' => 'required|email|max:255|unique:users',
        ]);

        // Generar una contraseña
        $data['password'] = str_random(8);
        // Creamos el usuario
        $user = User::create($data);
        // Asignamos los roles
            // preguntamos si el usuario lleno los campos
            // en este caso los checkbox para que asigne los roles
        if($request->filled('roles'))
        {
            $user->assignRole($request->roles);
        }

        // Asignamos los permisos
            // preguntamos si el usuario lleno los campos
            // en este caso los checkbox para que asigne los permisos
        if ($request->filled('permissions'))
        {
            $user->givePermissionTo($request->permissions);
        }

        // Enviamos el email con datos de acceso
        UserWasCreated::dispatch($user, $data['password']);

        // Regresamos una respuesta añ  usuario
        return redirect()->route('users.index')->with('message', ['success', __("Usuario creado correctamente")]);

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        $this->authorize('view', $user);
        return view('admin.user.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $this->authorize('update',$user);
        $roles = Role::with('permissions')->get();
        $permissions = Permission::pluck('name','id');
        $btnText = __("Editar Usuario");
        return view('admin.user.form', compact('user','btnText','roles','permissions'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UserRequest $userRequest, User $user)
    {
        $this->authorize('update',$user);
        $user->update($userRequest->validated() );
        return back()->with('message', ['success', __("Usuario actualizado correctamente")]);


    }


    public function destroy(User $user)
    {
        $this->authorize('delete', $user);
        try {
            $user->delete();
            return back()->with('message', ['success', __("Curso eliminado correctamente")]);
        } catch (\Exception $exception) {
            return back()->with('message', ['danger', __("Error eliminando el curso")]);
        }

//        return redirect()->route('users.index')->with('message', ['success', __("Usuario Eliminado")]);

    }
}

resources/views/admin/user/create.blade.php
@extends('admin.layout')
@section('header')

@endsection
@section('content')
    <div class="row">

        <form
                method="POST"
                {{--Si no exite el id del curso se va procesar store (guardar una nuevo )
                si lo tiene solo va actualizar el id del regustro y ademas le paso el slug --}}
                action="{{route('users.store', ['id' => $user->id])}}"
                {{--que no valide el navegador --}}
                novalidate
                {{--subida de archivos --}}
                enctype="multipart/form-data"
        >

            @csrf


            <div class="col-md-6">

                <div class="box box-warning">
                    <div class="box-header">
                        <h3 class="box-title">Datos Personales</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }} has-feedback">
                            <label for="name">
                                {{ __("Nombre") }}
                            </label>
                            <input
                                    name="name"
                                    id="name"
                                    class="form-control"
                                    value="{{ old('name') }}"

                            />

                            @if ($errors->has('name'))
                                <span class="help-block" role="alert">
                                                {{ $errors->first('name') }}
                                </span>
                            @endif
                        </div>
                        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }} has-feedback">
                            <label for="email">
                                {{ __("Email") }}
                            </label>
                            <input
                                    type="email"
                                    name="email"
                                    id="email"
                                    class="form-control"
                                    value="{{ old('email') }}"

                            />

                            @if ($errors->has('email'))
                                <span class="help-block" role="alert">
                                                {{ $errors->first('email') }}
                                </span>
                            @endif
                        </div>
                        <div class="form-group col-md-6">
                            <label for="">Roles</label>
                            @include('admin.roles.checkboxes')
                        </div>
                        <div class="form-group col-md-6">
                            <label for="">Roles</label>
                            @include('admin.permissions.checkboxes', ['model' => $user])
                        </div>

                        <span class="help-block">La contraseña sera generada y enviada al usuario via Email</span>
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary btn-block">
                                {{ __($btnText) }}
                            </button>
                        </div>
                    </div>
                </div>
            </div>

        </form>

    </div>

@endsection

resources/views/admin/user/form.blade.php
@extends('admin.layout')
@section('header')

@endsection
@section('content')
    <div class="row">

        <form
                method="POST"
                {{--Si no exite el id del curso se va procesar store (guardar una nuevo )
                si lo tiene solo va actualizar el id del regustro y ademas le paso el slug --}}
                action="{{route('users.update', ['id' => $user->id])}}"
                {{--que no valide el navegador --}}
                novalidate
                {{--subida de archivos --}}
                enctype="multipart/form-data"
        >

            @csrf  @method('PUT')


            <div class="col-md-6">

                <div class="box box-warning">
                    <div class="box-header">
                        <h3 class="box-title">Datos Personales</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }} has-feedback">
                            <label for="name">
                                {{ __("Nombre") }}
                            </label>
                            <input
                                    name="name"
                                    id="name"
                                    class="form-control"
                                    value="{{ old('name') ?: $user->name }}"

                            />

                            @if ($errors->has('name'))
                                <span class="help-block" role="alert">
                                                {{ $errors->first('name') }}
                                </span>
                            @endif
                        </div>
                        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }} has-feedback">
                            <label for="email">
                                {{ __("Email") }}
                            </label>
                            <input
                                    type="email"
                                    name="email"
                                    id="email"
                                    class="form-control"
                                    value="{{ old('email') ?: $user->email }}"

                            />

                            @if ($errors->has('email'))
                                <span class="help-block" role="alert">
                                                {{ $errors->first('email') }}
                                </span>
                            @endif
                        </div>

                        <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }} has-feedback">
                            <label for="password">
                                {{ __("Contraseña") }}
                            </label>
                            <input
                                    type="password"
                                    name="password"
                                    id="password"
                                    class="form-control"

                            />

                            @if ($errors->has('password'))
                                <span class="help-block" role="alert">
                                                {{ $errors->first('password') }}
                                </span>
                            @endif
                            <span class="help-block">
                                                  {{ __("Dejar en blanco si no quieres cambiar la contraseña") }}
                                </span>
                        </div>

                        <div class="form-group">
                            <label for="password">
                                {{ __("Repite Contraseña") }}
                            </label>
                            <input
                                    type="password"
                                    name="password_confirmation"
                                    id="password_confirmation"
                                    class="form-control"

                            />

                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-primary btn-block">
                                {{ __($btnText) }}
                            </button>
                        </div>
                    </div>
                </div>
            </div>

        </form>
            <div class="col-md-6">

                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Roles</h3>
                    </div>
                    <div class="box-body">
                        @role('Admin')
                        {{--Y pasarle al usuario a quien actualizar su rol --}}
                        <form method="POST" action="{{ route('users.roles.update', $user) }}">
                           @csrf @method('PUT')
                            @include('admin.roles.checkboxes')
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary btn-block">
                                    {{ __("Actualizar Roles") }}
                                </button>
                            </div>
                        </form>
                        @else
                            <ul class="list-group">
                                @forelse ($user->roles as $role)
                                    <li class="list-group-item">{{ $role->name }}</li>
                                @empty
                                    <li class="list-group-item">No tiene roles</li>
                                @endforelse
                            </ul>
                          @endrole

                    </div>
                </div>
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Permisos</h3>
                    </div>
                    <div class="box-body">
                        @role('Admin')
                        {{--Y pasarle al usuario a quien actualizar su rol --}}
                        <form method="POST" action="{{ route('users.permissions.update', $user) }}">
                            @csrf @method('PUT')
                            @include('admin.permissions.checkboxes', ['model' => $user])
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary btn-block">
                                    {{ __("Actualizar Permisos") }}
                                </button>
                            </div>
                        </form>
                        @else
                            <ul class="list-group">
                                @forelse ($user->permissions as $permission)
                                    <li class="list-group-item">{{ $permission->name }}</li>
                                @empty
                                    <li class="list-group-item">No tiene permisos</li>
                                @endforelse
                            </ul>
                         @endrole

                    </div>
                </div>

            </div>

    </div>

@endsection

resources/views/admin/user/index.blade.php
@extends('admin.layout')
@section('header')
    <h1>
        USUARIOS
        <small>Listado</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i>Inicio</a></li>
        <li class="active">Usuarios</li>
        @can('create', $users->first())
            <a href="{{ route('users.create') }}" class="btn btn-primary pull-right">
                <i class="fa fa-plus"></i>  Crear usuario
            </a>
        @endcan

    </ol>
@endsection
@section('content')
    <div class="box box-primary">
        <div class="box-header">
            <h3 class="box-title">Listado de Usuario</h3>
            <button class="btn btn-primary pull-right" data-toggle="modal" data-target="#myModal"><i class="fa fa-plus"></i> Crear Publicacion</button>

        </div>
        <!-- /.box-header -->
        <div class="box-body">
            <table id="users-table" class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Nombre</th>
                    <th>Email</th>
                    <th>Roles</th>
                    <th>Acciones</th>
                </tr>
                </thead>
                <tbody>
                @forelse($users as $user)
                    @can('view', $user)
                    <tr>
                        <td>{{ $user->id }}</td>
                        <td>{{ $user->name }}</td>
                        <td>{{ $user->email }}</td>
                        <td>{{ $user->getRoleNames()->implode(', ') }}</td>
                        <td>

                            @can('view', $user)
                            <a href="{{ route('users.show',$user) }}"  class="btn btn-xs btn-default"><i class="fa fa-eye"></i></a>
                            @endcan

                             @can('update', $user)
                            <a href="{{ route('users.edit',$user) }}" class="btn btn-xs btn-info"><i class="fa fa-pencil"></i></a>
                            @endcan

                            @can('delete', $user)
                            <form method="POST"
                                  action="{{ route('users.destroy', $user) }}"
                                  style="display: inline">
                                {{ csrf_field() }} {{ method_field('DELETE') }}
                                <button class="btn btn-xs btn-danger"
                                        onclick="return confirm('¿Estás seguro de querer eliminar a este usuario?')"
                                ><i class="fa fa-times"></i></button>
                            </form>
                            @endcan

                        </td>
                    </tr>
                    @endcan
                @empty   {{--le dices que no hay cursos --}}
                <div class="alert alert-dark">
                    {{ __("No hay ningún curso disponible") }}
                </div>

                @endforelse

                </tbody>
            </table>
        </div>
        <!-- /.box-body -->
    </div>
@endsection
@section('scripts')

@endsection
@push('styles')
    <link href="/css/datatables.css" rel="stylesheet">
@endpush
@push('scripts')
    <script src="/js/datatables.js" ></script>
    <script>
        $(function () {
            $('#users-table').DataTable({
                "paging": true,
                "lengthChange": false,
                "searching": false,
                "ordering": true,
                "info": true,
                "autoWidth": false
            });
        });
    </script>
@endpush

resources/views/admin/user/show.blade.php
@extends('admin.layout')

@section('content')
    <div class="row">
        <div class="col-md-3">
            <div class="box box-primary">
                <div class="box-body box-profile">
                    <img class="profile-user-img img-responsive img-circle"
                         src="https://adminlte.io/themes/AdminLTE/dist/img/user2-160x160.jpg"
                         alt="{{ $user->name }}">

                    <h3 class="profile-username text-center">{{ $user->name }}</h3>

                    <p class="text-muted text-center">{{ $user->getRoleNames()->implode(', ') }}</p>

                    <ul class="list-group list-group-unbordered">
                        <li class="list-group-item">
                            <b>Email</b> <a class="pull-right">{{ $user->email }}</a>
                        </li>
                        <li class="list-group-item">
                            <b>Publicaciones</b> <a class="pull-right">{{ $user->posts->count() }}</a>
                        </li>
                        @if ($user->roles->count())
                            <li class="list-group-item">
                                <b>Roles</b> <a class="pull-right">{{ $user->getRoleNames()->implode(', ') }}</a>
                            </li>
                        @endif
                    </ul>

                    <a href="{{ route('users.edit', $user) }}" class="btn btn-primary btn-block"><b>Editar</b></a>
                </div>
                <!-- /.box-body -->
            </div>
        </div>
        <div class="col-md-3">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Publicaciones</h3>
                </div>
                <div class="box-body">
                    @forelse ($user->posts as $post)
                        <a href="{{ route('posts.detail', $post) }}" target="_blank">
                            <strong>{{ $post->title }}</strong>
                        </a>
                        <br>
                        <small class="text-muted">Publicado el {{ $post->published_at->format('d/m/Y') }}</small>
                        <p class="text-muted">{{ $post->excerpt }}</p>
                        {{--En caso de que no sea la ultima publicacion --}}
                        {{--Desaparece el hr --}}
                        @unless ($loop->last)
                            <hr>
                        @endunless
                    @empty
                        <small class="text-muted">No tiene ninguna publicación</small>
                    @endforelse
                </div>
            </div>

        </div>
        <div class="col-md-3">
        <!--
                    tabla : model_has_roles
           role_id      model_type         model_id
            1	        App\User	        1
            2	        App\User	        1

            Significa que el usuario 1 osea que viene a hacer model_id = user_id
            tiene dos roles tanto admin y writer
        -->


            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Roles</h3>
                </div>
                <div class="box-body">
                    @forelse ($user->roles as $role)
                        <strong>{{ $role->name }}</strong>
                        @if ( $role->permissions->count() )
                            <br>
                            <small class="text-muted">
                                Permisos: {{ $role->permissions->pluck('name')->implode(', ') }}
                            </small>
                        @endif
                        @unless ($loop->last)
                            <hr>
                        @endunless
                    @empty
                        <small class="text-muted">No tiene ningún role asignado</small>
                    @endforelse
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <!--
                    tabla : model_has_permissions
           permission_id      model_type         model_id
            1	        App\User	        1
            2	        App\User	        1
            3	        App\User	        1

            Significa que el usuario 1 osea que viene a hacer model_id = user_id
            tiene 3 permisos tanto el 1 2 y el 3
            View posts | Create posts | Update posts
        -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Permisos adicionales</h3>
                </div>
                <div class="box-body">
                    @forelse ($user->permissions as $permission)
                        <strong>{{ $permission->name }}</strong>
                        @unless ($loop->last)
                            <hr>
                        @endunless
                    @empty
                        <small class="text-muted">No tiene permisos adicionales</small>
                    @endforelse
                </div>
            </div>
        </div>
    </div>

@stop