routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', 'PagesController@index')->name('pages.home');
Route::get('nosotros', 'PagesController@about')->name('pages.about');
Route::get('archivo', 'PagesController@archive')->name('pages.archive');
Route::get('contacto', 'PagesController@contact')->name('pages.contact');


// public function show(Post $post) recuerda que necesita un parametro $post = post
Route::get('blog/{post}', 'PostsController@show')->name('posts.detail');
// Buscar por categoria
Route::get('/categorias/{category}', 'CategoriesController@searchCategory')->name('search.category');
// Buscar por etiquetas - tags
Route::get('/tags/{tag}', 'TagsController@searchTag')->name('search.tag');
// Rutas para obtener y procesar la suscripcion
Route::group(['middleware' => ['auth']], function () {
    Route::group(["prefix" => "admin", 'namespace' => 'admin'], function() {


        Route::get('/', 'HomeController@index')->name('home');
        // Administrar los post y user
        Route::resource('posts', 'PostsController',['except' => 'show']);
        Route::resource('users', 'UsersController');
        // Administrar Roles
        Route::resource('roles', 'RolesController',['except' => 'show']);
        // Administrar Permisos
        Route::resource('permissions', 'PermissionsController', ['only' => ['index', 'edit', 'update']]);


        // Administrar los roles y solo pueden actualizar los roles los que tienen rol de admnistrador
        Route::middleware('role:Admin')->put('users/{user}/roles', 'UsersRolesController@update')->name('users.roles.update');
        // Administrar los permisos  y solo pueden actualizar los permisos los que tienen rol de admnistrador
        Route::middleware('role:Admin')->put('users/{user}/permissions', 'UsersPermissionsController@update')->name('users.permissions.update');

        // Administrar las photos
        Route::post('posts/{post}/photos', 'PhotoController@store')->name('posts.photos.store');
        Route::delete('photos/{photo}', 'PhotoController@destroy')->name('admin.photos.destroy');
    });

});

Route::auth();

app/Http/Controllers/Admin/PermissionsController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Spatie\Permission\Models\Permission;

class PermissionsController extends Controller
{
    public function index()
    {
        $this->authorize('view', new Permission);

        return view('admin.permissions.index',[
            'permissions' => Permission::all()
        ]);
    }

    public function edit(Permission $permission)
    {
        $this->authorize('update', $permission);

        $btnText = __("Editar Permiso");
        return view('admin.permissions.form', [
            'permission' => $permission,

        ],compact('btnText'));
    }

    public function update(Request $request, Permission $permission)
    {
        $this->authorize('update', $permission);

        $data = $request->validate(['display_name' => 'required']);

        $permission->update($data);

        return back()->with('message', ['success', __("El permiso ha sido actualizado")]);
    }

}

resources/views/admin/permissions/checkboxes.blade.php
@forelse ($permissions as $id => $name)
    <div class="checkbox">
        <label>
            {{--aqui hubo un problemas al momemtno de interactuar con la  variable $user y por eso le colocamos
            $model ya que lo vamos a llamar asi desde el archivo que lo requiera
             @include('admin.permissions.checkboxes', ['model' => $role])
             --}}
            <input name="permissions[]" type="checkbox" value="{{ $name }}"
                   {{--verificamos si el  rol tiene los mismo permisos que los que estan la tabla permiso a traves de su id
                   y tambien si realmente los permisos que tiene seleccionado actuamente
                   coincide con los nombre de los permisos(true|false)
                   --}}
                    {{
                     $model->permissions->contains($id) || collect( old('permissions') )->contains($name)
                     ? 'checked' : ''
                    }}>
            {{ $name }}
        </label>
    </div>

@empty

@endforelse

resources/views/admin/permissions/form.blade.php
@extends('admin.layout')
@section('header')

@endsection
@section('content')
    <div class="row">

        <form
                method="POST"
                {{--Si no exite el id del curso se va procesar store (guardar una nuevo )
                si lo tiene solo va actualizar el id del regustro y ademas le paso el slug --}}
                action="{{ ! $permission->id ? route('permissions.store') : route('permissions.update', ['id' => $permission->id])}}"
                {{--que no valide el navegador --}}
                novalidate

        >

            @if($permission->id)
                @method('PUT')
            @endif

            @csrf


            <div class="col-md-6">

                <div class="box box-warning">
                    <div class="box-header">
                        <h3 class="box-title">permissions</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">

                        <div class="form-group has-feedback">
                            <label for="name">
                                {{ __("Identificador") }}
                            </label>
                            <input
                                    name="name"
                                    id="name"
                                    class="form-control"
                                    value="{{ $permission->name }}"
                                    disabled
                            />
                        </div>

                        <div class="form-group{{ $errors->has('display_name') ? ' has-error' : '' }} has-feedback">
                            <label for="display_name">
                                {{ __("Nombre") }}
                            </label>
                            <input
                                    name="display_name"
                                    id="display_name"
                                    class="form-control"
                                    value="{{ old('display_name') ?: $permission->display_name }}"

                            />

                            @if ($errors->has('display_name'))
                                <span class="help-block" role="alert">
                                                {{ $errors->first('display_name') }}
                                </span>
                            @endif
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-primary btn-block">
                                {{ __($btnText) }}
                            </button>
                        </div>
                    </div>
                </div>
            </div>

        </form>


    </div>

@endsection

resources/views/admin/permissions/index.blade.php
@extends('admin.layout')

@section('header')
    <h1>
        Permisos
        <small>Listado</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="{{ route('home') }}"><i class="fa fa-dashboard"></i> Inicio</a></li>
        <li class="active">Permisos</li>
    </ol>
@stop

@section('content')
    <div class="box box-primary">
        <div class="box-header">
            <h3 class="box-title">Listado de Permisos</h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            <table id="roles-table" class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Identificador</th>
                    <th>Nombre</th>
                    <th>Acciones</th>
                </tr>
                </thead>
                <tbody>
                @foreach ($permissions as $permission)
                    <tr>
                        <td>{{ $permission->id }}</td>
                        <td>{{ $permission->name }}</td>
                        <td>{{ $permission->display_name }}</td>
                        <td>
                            @can('update', $permission)
                            <a href="{{ route('permissions.edit', $permission) }}"
                               class="btn btn-xs btn-info"
                            ><i class="fa fa-pencil"></i></a>
                            @endcan
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
        <!-- /.box-body -->
    </div>
    <!-- /.box -->
@stop

@push('styles')
    <link href="/css/datatables.css" rel="stylesheet">
@endpush
@push('scripts')
    <script src="/js/datatables.js" ></script>
    <script>
        $(function () {
            $('#roles-table').DataTable({
                "paging": true,
                "lengthChange": false,
                "searching": false,
                "ordering": true,
                "info": true,
                "autoWidth": false
            });
        });
    </script>
@endpush